version: '2'
services:
    nanoinventory-app:
        image: nanoinventory
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://nanoinventory-mysql:3306/nanoinventory?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    nanoinventory-mysql:
        extends:
            file: mysql.yml
            service: nanoinventory-mysql
